name: yolov8_seg          # 환경 이름
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipython
  - ipykernel
  - notebook
  - jupyterlab
  - pip:
      - ultralytics>=8.0.20    # YOLOv8 (Segmentation 포함)
      - torch>=1.13            # PyTorch
      - torchvision>=0.14
      - opencv-python>=4.5     # 비디오 입출력
      - matplotlib             # 결과 시각화
      - notebook               # Jupyter Notebook
      - ipywidgets             # 인터랙티브 위젯 (선택)
      - tqdm                   # 진행바
